# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/nook/Desktop/nook_Pipeline/Project/redShift_multimatte/pt_RSMultiMatteTool/ui.ui'
#
# Created: Tue Jul 18 15:31:35 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Renderer_optionGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.Renderer_optionGroupBox.setObjectName("Renderer_optionGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.Renderer_optionGroupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtGui.QLabel(self.Renderer_optionGroupBox)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.Renderer_comboBox = QtGui.QComboBox(self.Renderer_optionGroupBox)
        self.Renderer_comboBox.setObjectName("Renderer_comboBox")
        self.Renderer_comboBox.addItem("")
        self.Renderer_comboBox.addItem("")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.Renderer_comboBox)
        self.verticalLayout_3.addWidget(self.Renderer_optionGroupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.ObjectID_tab = QtGui.QWidget()
        self.ObjectID_tab.setObjectName("ObjectID_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.ObjectID_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ObjectID_topLayout = QtGui.QHBoxLayout()
        self.ObjectID_topLayout.setObjectName("ObjectID_topLayout")
        self.objectID_label = QtGui.QLabel(self.ObjectID_tab)
        self.objectID_label.setObjectName("objectID_label")
        self.ObjectID_topLayout.addWidget(self.objectID_label)
        self.objectID_refresh_button = QtGui.QPushButton(self.ObjectID_tab)
        self.objectID_refresh_button.setObjectName("objectID_refresh_button")
        self.ObjectID_topLayout.addWidget(self.objectID_refresh_button)
        self.verticalLayout.addLayout(self.ObjectID_topLayout)
        self.ObjectID_listWidget = QtGui.QListWidget(self.ObjectID_tab)
        self.ObjectID_listWidget.setObjectName("ObjectID_listWidget")
        self.verticalLayout.addWidget(self.ObjectID_listWidget)
        self.ObjectID_option = QtGui.QGroupBox(self.ObjectID_tab)
        self.ObjectID_option.setObjectName("ObjectID_option")
        self.formLayout = QtGui.QFormLayout(self.ObjectID_option)
        self.formLayout.setObjectName("formLayout")
        self.ObjectID_Start_label = QtGui.QLabel(self.ObjectID_option)
        self.ObjectID_Start_label.setObjectName("ObjectID_Start_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ObjectID_Start_label)
        self.ObjectID_Start_LineEdit = QtGui.QLineEdit(self.ObjectID_option)
        self.ObjectID_Start_LineEdit.setObjectName("ObjectID_Start_LineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ObjectID_Start_LineEdit)
        self.ObjectID_Increment_label = QtGui.QLabel(self.ObjectID_option)
        self.ObjectID_Increment_label.setObjectName("ObjectID_Increment_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ObjectID_Increment_label)
        self.ObjectID_Increment_LineEdit = QtGui.QLineEdit(self.ObjectID_option)
        self.ObjectID_Increment_LineEdit.setObjectName("ObjectID_Increment_LineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ObjectID_Increment_LineEdit)
        self.verticalLayout.addWidget(self.ObjectID_option)
        self.ObjectID_SetI_button = QtGui.QPushButton(self.ObjectID_tab)
        self.ObjectID_SetI_button.setObjectName("ObjectID_SetI_button")
        self.verticalLayout.addWidget(self.ObjectID_SetI_button)
        self.tabWidget.addTab(self.ObjectID_tab, "")
        self.MaterialID_tab = QtGui.QWidget()
        self.MaterialID_tab.setObjectName("MaterialID_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.MaterialID_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.matteriaID_topLayout = QtGui.QHBoxLayout()
        self.matteriaID_topLayout.setObjectName("matteriaID_topLayout")
        self.materialD_label = QtGui.QLabel(self.MaterialID_tab)
        self.materialD_label.setObjectName("materialD_label")
        self.matteriaID_topLayout.addWidget(self.materialD_label)
        self.materialD_refresh = QtGui.QPushButton(self.MaterialID_tab)
        self.materialD_refresh.setObjectName("materialD_refresh")
        self.matteriaID_topLayout.addWidget(self.materialD_refresh)
        self.verticalLayout_2.addLayout(self.matteriaID_topLayout)
        self.MatterialID_listWidget = QtGui.QListWidget(self.MaterialID_tab)
        self.MatterialID_listWidget.setObjectName("MatterialID_listWidget")
        self.verticalLayout_2.addWidget(self.MatterialID_listWidget)
        self.MaterialI_option = QtGui.QGroupBox(self.MaterialID_tab)
        self.MaterialI_option.setObjectName("MaterialI_option")
        self.formLayout_2 = QtGui.QFormLayout(self.MaterialI_option)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.MaterialID_Start_label = QtGui.QLabel(self.MaterialI_option)
        self.MaterialID_Start_label.setObjectName("MaterialID_Start_label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.MaterialID_Start_label)
        self.MaterialID_Start_LineEdit = QtGui.QLineEdit(self.MaterialI_option)
        self.MaterialID_Start_LineEdit.setObjectName("MaterialID_Start_LineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.MaterialID_Start_LineEdit)
        self.MaterialID_Increment_label = QtGui.QLabel(self.MaterialI_option)
        self.MaterialID_Increment_label.setObjectName("MaterialID_Increment_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.MaterialID_Increment_label)
        self.MaterialID_Increment_LineEdit = QtGui.QLineEdit(self.MaterialI_option)
        self.MaterialID_Increment_LineEdit.setObjectName("MaterialID_Increment_LineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.MaterialID_Increment_LineEdit)
        self.verticalLayout_2.addWidget(self.MaterialI_option)
        self.SetMaterialID_button = QtGui.QPushButton(self.MaterialID_tab)
        self.SetMaterialID_button.setObjectName("SetMaterialID_button")
        self.verticalLayout_2.addWidget(self.SetMaterialID_button)
        self.tabWidget.addTab(self.MaterialID_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.separate_line = QtGui.QFrame(self.centralwidget)
        self.separate_line.setFrameShape(QtGui.QFrame.VLine)
        self.separate_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.separate_line.setObjectName("separate_line")
        self.horizontalLayout_2.addWidget(self.separate_line)
        self.puzzleMatte_Layout = QtGui.QVBoxLayout()
        self.puzzleMatte_Layout.setObjectName("puzzleMatte_Layout")
        self.puzzleMatteID_topLayout = QtGui.QHBoxLayout()
        self.puzzleMatteID_topLayout.setSpacing(6)
        self.puzzleMatteID_topLayout.setObjectName("puzzleMatteID_topLayout")
        self.PuzzleID_label = QtGui.QLabel(self.centralwidget)
        self.PuzzleID_label.setObjectName("PuzzleID_label")
        self.puzzleMatteID_topLayout.addWidget(self.PuzzleID_label)
        self.PuzzleID_refresh_button = QtGui.QPushButton(self.centralwidget)
        self.PuzzleID_refresh_button.setObjectName("PuzzleID_refresh_button")
        self.puzzleMatteID_topLayout.addWidget(self.PuzzleID_refresh_button)
        self.puzzleMatte_Layout.addLayout(self.puzzleMatteID_topLayout)
        self.PuzzleID_listWidget = QtGui.QListWidget(self.centralwidget)
        self.PuzzleID_listWidget.setObjectName("PuzzleID_listWidget")
        self.puzzleMatte_Layout.addWidget(self.PuzzleID_listWidget)
        self.PuzzleID_option = QtGui.QGroupBox(self.centralwidget)
        self.PuzzleID_option.setObjectName("PuzzleID_option")
        self.formLayout_3 = QtGui.QFormLayout(self.PuzzleID_option)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.PuzzleID_Prefix_label = QtGui.QLabel(self.PuzzleID_option)
        self.PuzzleID_Prefix_label.setObjectName("PuzzleID_Prefix_label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.PuzzleID_Prefix_label)
        self.PuzzleID_Prefix_LineEdit = QtGui.QLineEdit(self.PuzzleID_option)
        self.PuzzleID_Prefix_LineEdit.setObjectName("PuzzleID_Prefix_LineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.PuzzleID_Prefix_LineEdit)
        self.PuzzleID_Name_label = QtGui.QLabel(self.PuzzleID_option)
        self.PuzzleID_Name_label.setObjectName("PuzzleID_Name_label")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.PuzzleID_Name_label)
        self.PuzzleID_Name_LineEdit = QtGui.QLineEdit(self.PuzzleID_option)
        self.PuzzleID_Name_LineEdit.setObjectName("PuzzleID_Name_LineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.PuzzleID_Name_LineEdit)
        self.puzzleMatte_Layout.addWidget(self.PuzzleID_option)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.puzzleMatte_Layout.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.puzzleMatte_Layout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_optionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Renderer :", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Redshift", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Vray", None, QtGui.QApplication.UnicodeUTF8))
        self.objectID_label.setText(QtGui.QApplication.translate("MainWindow", "Object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.objectID_refresh_button.setText(QtGui.QApplication.translate("MainWindow", "refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_Start_label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_Increment_label.setText(QtGui.QApplication.translate("MainWindow", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_SetI_button.setText(QtGui.QApplication.translate("MainWindow", "Set object ID to selection", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ObjectID_tab), QtGui.QApplication.translate("MainWindow", "Object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.materialD_label.setText(QtGui.QApplication.translate("MainWindow", "Material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.materialD_refresh.setText(QtGui.QApplication.translate("MainWindow", "refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialI_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Start_label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Increment_label.setText(QtGui.QApplication.translate("MainWindow", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.SetMaterialID_button.setText(QtGui.QApplication.translate("MainWindow", "Set material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MaterialID_tab), QtGui.QApplication.translate("MainWindow", "Material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_label.setText(QtGui.QApplication.translate("MainWindow", "Puzzle matte", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_refresh_button.setText(QtGui.QApplication.translate("MainWindow", "refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_Prefix_label.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_Name_label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Create from selection", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

