# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/nook/Desktop/nook_Pipeline/Project/redShift_multimatte/pt_RSMultiMatteTool/ui.ui'
#
# Created: Fri Jul 21 10:28:31 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Renderer_optionGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.Renderer_optionGroupBox.setObjectName("Renderer_optionGroupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Renderer_optionGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.Renderer_optionGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.Renderer_comboBox = QtGui.QComboBox(self.Renderer_optionGroupBox)
        self.Renderer_comboBox.setObjectName("Renderer_comboBox")
        self.Renderer_comboBox.addItem("")
        self.Renderer_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.Renderer_comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.setting_button = QtGui.QPushButton(self.Renderer_optionGroupBox)
        self.setting_button.setEnabled(False)
        self.setting_button.setObjectName("setting_button")
        self.horizontalLayout_3.addWidget(self.setting_button)
        self.verticalLayout_3.addWidget(self.Renderer_optionGroupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.Proxy_ObjectID_tab = QtGui.QWidget()
        self.Proxy_ObjectID_tab.setObjectName("Proxy_ObjectID_tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Proxy_ObjectID_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ProxyObjID_label = QtGui.QLabel(self.Proxy_ObjectID_tab)
        self.ProxyObjID_label.setObjectName("ProxyObjID_label")
        self.horizontalLayout.addWidget(self.ProxyObjID_label)
        self.ProxyObjID_refresh_button = QtGui.QPushButton(self.Proxy_ObjectID_tab)
        self.ProxyObjID_refresh_button.setObjectName("ProxyObjID_refresh_button")
        self.horizontalLayout.addWidget(self.ProxyObjID_refresh_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.ProxyObjID_listWidget = QtGui.QListWidget(self.Proxy_ObjectID_tab)
        self.ProxyObjID_listWidget.setObjectName("ProxyObjID_listWidget")
        self.verticalLayout_4.addWidget(self.ProxyObjID_listWidget)
        self.Proxy_option = QtGui.QGroupBox(self.Proxy_ObjectID_tab)
        self.Proxy_option.setObjectName("Proxy_option")
        self.formLayout_5 = QtGui.QFormLayout(self.Proxy_option)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.ProxyObjID_name_label = QtGui.QLabel(self.Proxy_option)
        self.ProxyObjID_name_label.setObjectName("ProxyObjID_name_label")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.ProxyObjID_name_label)
        self.ProxyObjID_name_lineEdit = QtGui.QLineEdit(self.Proxy_option)
        self.ProxyObjID_name_lineEdit.setObjectName("ProxyObjID_name_lineEdit")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.ProxyObjID_name_lineEdit)
        self.ProxyObjID_Start_label = QtGui.QLabel(self.Proxy_option)
        self.ProxyObjID_Start_label.setObjectName("ProxyObjID_Start_label")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.ProxyObjID_Start_label)
        self.ProxyObjID_Start_lineEdit = QtGui.QLineEdit(self.Proxy_option)
        self.ProxyObjID_Start_lineEdit.setObjectName("ProxyObjID_Start_lineEdit")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.ProxyObjID_Start_lineEdit)
        self.ProxyObjID_Increment_label = QtGui.QLabel(self.Proxy_option)
        self.ProxyObjID_Increment_label.setObjectName("ProxyObjID_Increment_label")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.ProxyObjID_Increment_label)
        self.ProxyObjID_Increment_lineEdit = QtGui.QLineEdit(self.Proxy_option)
        self.ProxyObjID_Increment_lineEdit.setObjectName("ProxyObjID_Increment_lineEdit")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.ProxyObjID_Increment_lineEdit)
        self.ProxyObjID_ObjectID_checkBox = QtGui.QCheckBox(self.Proxy_option)
        self.ProxyObjID_ObjectID_checkBox.setObjectName("ProxyObjID_ObjectID_checkBox")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.ProxyObjID_ObjectID_checkBox)
        self.ProxyObjID_Override_label = QtGui.QLabel(self.Proxy_option)
        self.ProxyObjID_Override_label.setObjectName("ProxyObjID_Override_label")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.ProxyObjID_Override_label)
        self.verticalLayout_4.addWidget(self.Proxy_option)
        self.ProxyObjID_SetProxyObjID_button = QtGui.QPushButton(self.Proxy_ObjectID_tab)
        self.ProxyObjID_SetProxyObjID_button.setObjectName("ProxyObjID_SetProxyObjID_button")
        self.verticalLayout_4.addWidget(self.ProxyObjID_SetProxyObjID_button)
        self.tabWidget.addTab(self.Proxy_ObjectID_tab, "")
        self.ObjectID_tab = QtGui.QWidget()
        self.ObjectID_tab.setObjectName("ObjectID_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.ObjectID_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ObjectID_topLayout = QtGui.QHBoxLayout()
        self.ObjectID_topLayout.setObjectName("ObjectID_topLayout")
        self.objectID_label = QtGui.QLabel(self.ObjectID_tab)
        self.objectID_label.setObjectName("objectID_label")
        self.ObjectID_topLayout.addWidget(self.objectID_label)
        self.objectID_refresh_button = QtGui.QPushButton(self.ObjectID_tab)
        self.objectID_refresh_button.setObjectName("objectID_refresh_button")
        self.ObjectID_topLayout.addWidget(self.objectID_refresh_button)
        self.verticalLayout.addLayout(self.ObjectID_topLayout)
        self.ObjectID_listWidget = QtGui.QListWidget(self.ObjectID_tab)
        self.ObjectID_listWidget.setObjectName("ObjectID_listWidget")
        self.verticalLayout.addWidget(self.ObjectID_listWidget)
        self.ObjectID_option = QtGui.QGroupBox(self.ObjectID_tab)
        self.ObjectID_option.setObjectName("ObjectID_option")
        self.formLayout = QtGui.QFormLayout(self.ObjectID_option)
        self.formLayout.setObjectName("formLayout")
        self.ObjectID_Start_label = QtGui.QLabel(self.ObjectID_option)
        self.ObjectID_Start_label.setObjectName("ObjectID_Start_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ObjectID_Start_label)
        self.ObjectID_Start_LineEdit = QtGui.QLineEdit(self.ObjectID_option)
        self.ObjectID_Start_LineEdit.setObjectName("ObjectID_Start_LineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ObjectID_Start_LineEdit)
        self.ObjectID_Increment_label = QtGui.QLabel(self.ObjectID_option)
        self.ObjectID_Increment_label.setObjectName("ObjectID_Increment_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ObjectID_Increment_label)
        self.ObjectID_Increment_LineEdit = QtGui.QLineEdit(self.ObjectID_option)
        self.ObjectID_Increment_LineEdit.setObjectName("ObjectID_Increment_LineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ObjectID_Increment_LineEdit)
        self.ObjectID_Name_label = QtGui.QLabel(self.ObjectID_option)
        self.ObjectID_Name_label.setObjectName("ObjectID_Name_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ObjectID_Name_label)
        self.ObjectID_Name_LineEdit = QtGui.QLineEdit(self.ObjectID_option)
        self.ObjectID_Name_LineEdit.setObjectName("ObjectID_Name_LineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ObjectID_Name_LineEdit)
        self.verticalLayout.addWidget(self.ObjectID_option)
        self.ObjectID_SetI_button = QtGui.QPushButton(self.ObjectID_tab)
        self.ObjectID_SetI_button.setObjectName("ObjectID_SetI_button")
        self.verticalLayout.addWidget(self.ObjectID_SetI_button)
        self.tabWidget.addTab(self.ObjectID_tab, "")
        self.MaterialID_tab = QtGui.QWidget()
        self.MaterialID_tab.setObjectName("MaterialID_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.MaterialID_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.matteriaID_topLayout = QtGui.QHBoxLayout()
        self.matteriaID_topLayout.setObjectName("matteriaID_topLayout")
        self.materialD_label = QtGui.QLabel(self.MaterialID_tab)
        self.materialD_label.setObjectName("materialD_label")
        self.matteriaID_topLayout.addWidget(self.materialD_label)
        self.materialD_refresh = QtGui.QPushButton(self.MaterialID_tab)
        self.materialD_refresh.setObjectName("materialD_refresh")
        self.matteriaID_topLayout.addWidget(self.materialD_refresh)
        self.verticalLayout_2.addLayout(self.matteriaID_topLayout)
        self.MatterialID_listWidget = QtGui.QListWidget(self.MaterialID_tab)
        self.MatterialID_listWidget.setObjectName("MatterialID_listWidget")
        self.verticalLayout_2.addWidget(self.MatterialID_listWidget)
        self.MaterialI_option = QtGui.QGroupBox(self.MaterialID_tab)
        self.MaterialI_option.setObjectName("MaterialI_option")
        self.formLayout_2 = QtGui.QFormLayout(self.MaterialI_option)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.MaterialID_Start_label = QtGui.QLabel(self.MaterialI_option)
        self.MaterialID_Start_label.setObjectName("MaterialID_Start_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.MaterialID_Start_label)
        self.MaterialID_Start_LineEdit = QtGui.QLineEdit(self.MaterialI_option)
        self.MaterialID_Start_LineEdit.setObjectName("MaterialID_Start_LineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.MaterialID_Start_LineEdit)
        self.MaterialID_Increment_label = QtGui.QLabel(self.MaterialI_option)
        self.MaterialID_Increment_label.setObjectName("MaterialID_Increment_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.MaterialID_Increment_label)
        self.MaterialID_Increment_LineEdit = QtGui.QLineEdit(self.MaterialI_option)
        self.MaterialID_Increment_LineEdit.setObjectName("MaterialID_Increment_LineEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.MaterialID_Increment_LineEdit)
        self.MaterialID_Select_label = QtGui.QLabel(self.MaterialI_option)
        self.MaterialID_Select_label.setObjectName("MaterialID_Select_label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.MaterialID_Select_label)
        self.MaterialID_Select_comboBox = QtGui.QComboBox(self.MaterialI_option)
        self.MaterialID_Select_comboBox.setObjectName("MaterialID_Select_comboBox")
        self.MaterialID_Select_comboBox.addItem("")
        self.MaterialID_Select_comboBox.addItem("")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.MaterialID_Select_comboBox)
        self.verticalLayout_2.addWidget(self.MaterialI_option)
        self.SetMaterialID_button = QtGui.QPushButton(self.MaterialID_tab)
        self.SetMaterialID_button.setObjectName("SetMaterialID_button")
        self.verticalLayout_2.addWidget(self.SetMaterialID_button)
        self.tabWidget.addTab(self.MaterialID_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.separate_line = QtGui.QFrame(self.centralwidget)
        self.separate_line.setFrameShape(QtGui.QFrame.VLine)
        self.separate_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.separate_line.setObjectName("separate_line")
        self.horizontalLayout_2.addWidget(self.separate_line)
        self.puzzleMatte_Layout = QtGui.QVBoxLayout()
        self.puzzleMatte_Layout.setObjectName("puzzleMatte_Layout")
        self.puzzleMatteID_topLayout = QtGui.QHBoxLayout()
        self.puzzleMatteID_topLayout.setSpacing(6)
        self.puzzleMatteID_topLayout.setObjectName("puzzleMatteID_topLayout")
        self.PuzzleID_label = QtGui.QLabel(self.centralwidget)
        self.PuzzleID_label.setObjectName("PuzzleID_label")
        self.puzzleMatteID_topLayout.addWidget(self.PuzzleID_label)
        self.PuzzleID_refresh_button = QtGui.QPushButton(self.centralwidget)
        self.PuzzleID_refresh_button.setObjectName("PuzzleID_refresh_button")
        self.puzzleMatteID_topLayout.addWidget(self.PuzzleID_refresh_button)
        self.puzzleMatte_Layout.addLayout(self.puzzleMatteID_topLayout)
        self.PuzzleID_listWidget = QtGui.QListWidget(self.centralwidget)
        self.PuzzleID_listWidget.setObjectName("PuzzleID_listWidget")
        self.puzzleMatte_Layout.addWidget(self.PuzzleID_listWidget)
        self.PuzzleID_option = QtGui.QGroupBox(self.centralwidget)
        self.PuzzleID_option.setObjectName("PuzzleID_option")
        self.formLayout_3 = QtGui.QFormLayout(self.PuzzleID_option)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.PuzzleID_Prefix_label = QtGui.QLabel(self.PuzzleID_option)
        self.PuzzleID_Prefix_label.setObjectName("PuzzleID_Prefix_label")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.PuzzleID_Prefix_label)
        self.PuzzleID_Prefix_LineEdit = QtGui.QLineEdit(self.PuzzleID_option)
        self.PuzzleID_Prefix_LineEdit.setObjectName("PuzzleID_Prefix_LineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.PuzzleID_Prefix_LineEdit)
        self.PuzzleID_Name_label = QtGui.QLabel(self.PuzzleID_option)
        self.PuzzleID_Name_label.setObjectName("PuzzleID_Name_label")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.PuzzleID_Name_label)
        self.PuzzleID_Name_LineEdit = QtGui.QLineEdit(self.PuzzleID_option)
        self.PuzzleID_Name_LineEdit.setObjectName("PuzzleID_Name_LineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.PuzzleID_Name_LineEdit)
        self.puzzleMatte_Layout.addWidget(self.PuzzleID_option)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.puzzleMatte_Layout.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.puzzleMatte_Layout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_optionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Renderer :", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Redshift", None, QtGui.QApplication.UnicodeUTF8))
        self.Renderer_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Vray", None, QtGui.QApplication.UnicodeUTF8))
        self.setting_button.setText(QtGui.QApplication.translate("MainWindow", "setting", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_label.setText(QtGui.QApplication.translate("MainWindow", "Proxy ObjectID", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_refresh_button.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.Proxy_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_name_label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_Start_label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_Increment_label.setText(QtGui.QApplication.translate("MainWindow", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_ObjectID_checkBox.setText(QtGui.QApplication.translate("MainWindow", "ObjectID", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_Override_label.setText(QtGui.QApplication.translate("MainWindow", "Override :", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyObjID_SetProxyObjID_button.setText(QtGui.QApplication.translate("MainWindow", "Set ObjectID for Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Proxy_ObjectID_tab), QtGui.QApplication.translate("MainWindow", "Proxy_ObjectID", None, QtGui.QApplication.UnicodeUTF8))
        self.objectID_label.setText(QtGui.QApplication.translate("MainWindow", "Object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.objectID_refresh_button.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_Start_label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_Increment_label.setText(QtGui.QApplication.translate("MainWindow", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_Name_label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ObjectID_SetI_button.setText(QtGui.QApplication.translate("MainWindow", "Set object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ObjectID_tab), QtGui.QApplication.translate("MainWindow", "Object ID", None, QtGui.QApplication.UnicodeUTF8))
        self.materialD_label.setText(QtGui.QApplication.translate("MainWindow", "Material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.materialD_refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialI_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Start_label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Increment_label.setText(QtGui.QApplication.translate("MainWindow", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Select_label.setText(QtGui.QApplication.translate("MainWindow", "Select on", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Select_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mesh Node", None, QtGui.QApplication.UnicodeUTF8))
        self.MaterialID_Select_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Material Node", None, QtGui.QApplication.UnicodeUTF8))
        self.SetMaterialID_button.setText(QtGui.QApplication.translate("MainWindow", "Set material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MaterialID_tab), QtGui.QApplication.translate("MainWindow", "Material ID", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_label.setText(QtGui.QApplication.translate("MainWindow", "Puzzle matte", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_refresh_button.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_option.setTitle(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_Prefix_label.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.PuzzleID_Name_label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Create from selection", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

